name: thimar_driver
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.1
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  logger: ^2.6.1
  get_it: ^8.2.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  url_launcher: ^6.3.2
  fluttertoast: ^9.0.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  auto_size_text: ^3.0.0
  intl: ^0.20.2
  flutter_localization: ^0.3.3
  country_code_picker: ^3.4.0
  circular_countdown_timer: ^0.2.4
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.1.1
  animated_confirm_dialog: ^1.0.2
  http_parser: ^4.1.2
  flutter_html: ^3.0.0
  dotted_border: ^2.1.0
  google_maps_flutter: ^2.13.1
  location: ^8.0.1
  flutter_launcher_icons: ^0.14.4
  dotted_line: ^3.2.3
  easy_localization: ^3.0.8
  flash: ^3.1.1
  lottie: ^3.3.2
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - assets/translations/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21